# fly.toml app configuration file generated for member-only-app on 2024-05-11T10:32:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'member-only-app'
primary_region = 'den'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
